Repository joostlek/python-overseerr, pull requests merged in 2025-02, with the labels that each got.

#67 ✨ Initial Issue support
  src/python_overseerr/__init__.py
  src/python_overseerr/models.py
  src/python_overseerr/overseerr.py
  tests/__snapshots__/test_overseerr.ambr
  tests/fixtures/issue.json
  tests/fixtures/issue_count.json
  tests/test_overseerr.py
Labels: new-feature

#68 Add funding info
  .github/FUNDING.yaml
Labels: enhancement

#80 Fix enum name
  src/python_overseerr/models.py
  tests/__snapshots__/test_overseerr.ambr
Labels: bugfix
